export interface CommentOptions {
  title?: string;
  footer?: string;
  collapsed?: boolean;
}

export function formatComment(
  mermaidGraph: string,
  options: CommentOptions = {}
): string {
  const title = options.title ?? "📦 Dependency Graph";
  const footer =
    options.footer ??
    "*Generated by [depgraph-action](https://github.com/depgraph-action)*";

  const graphBlock = options.collapsed
    ? `<details>\n<summary>Show graph</summary>\n\n\`\`\`mermaid\n${mermaidGraph}\n\`\`\`\n</details>`
    : `\`\`\`mermaid\n${mermaidGraph}\n\`\`\``;

  return [
    `## ${title}`,
    "",
    graphBlock,
    "",
    footer,
  ].join("\n");
}

export function formatErrorComment(error: Error): string {
  return [
    "## 📦 Dependency Graph",
    "",
    "> ⚠️ **depgraph-action** failed to generate the dependency graph.",
    "",
    `\`\`\`\n${error.message}\n\`\`\``,
  ].join("\n");
}
