import { Graph } from './packageParser';

export function renderMermaidGraph(graph: Graph): string {
  const lines: string[] = ['```mermaid', 'graph TD'];

  const nodeIds = new Map<string, string>();
  let counter = 0;

  const getNodeId = (name: string): string => {
    if (!nodeIds.has(name)) {
      nodeIds.set(name, `pkg${counter++}`);
    }
    return nodeIds.get(name)!;
  };

  // Register all nodes first
  for (const node of graph.nodes) {
    const id = getNodeId(node.name);
    const label = node.version ? `${node.name}@${node.version}` : node.name;
    lines.push(`  ${id}["${label}"]`);
  }

  // Add edges
  for (const edge of graph.edges) {
    const fromId = getNodeId(edge.from);
    const toId = getNodeId(edge.to);
    lines.push(`  ${fromId} --> ${toId}`);
  }

  lines.push('```');
  return lines.join('\n');
}

export function renderMarkdownComment(graph: Graph, prNumber: number): string {
  const mermaid = renderMermaidGraph(graph);
  const nodeCount = graph.nodes.length;
  const edgeCount = graph.edges.length;

  return [
    '## 📦 Dependency Graph',
    '',
    `> Auto-generated for PR #${prNumber} — ${nodeCount} packages, ${edgeCount} dependencies`,
    '',
    mermaid,
    '',
    `<sub>Generated by [depgraph-action](https://github.com/depgraph-action)</sub>`,
  ].join('\n');
}
